---
title: "NaOH"
author: "Romanov Stanislav"
date: "21 10 2021"
tags: ["NaOH"]
---

### 10N NaOH

```{r echo=FALSE}

blogdown::shortcode("notice", "info",.content = "10N (десяти нормальный) NaOH используется для быстрого титрования буферных растворов а так же как стоковый раствор щелочи. Нормальность - эквивалент молярности, применительно к щелочи указывает количество растворенных OH-групп. Так что 10N NaOH в точности равно 10M NaOH.")
```

```{r echo=FALSE}

blogdown::shortcode("notice", "info",.content = "NaOH очень гигроскопичен. Готовить стоковый раствор имеет смысл только из свежего порошка или гранул щелочи.")
```

-   Для получения нужного объема 10N NaOH требуется навесить указанное количество NaOH. Реакция протекает с интенсивным выделением тепла, так что сток получают постепенным добавлением NaOH к mQ ( 80% от запланированного объема) в закаленной стеклянной бутылке.

+------------------+-------+-------+-------+-------+-------+-------+
|                  | 10 мл | 20 мл | 25 мл | 30 мл | 40 мл | 50 мл |
+==================+=======+=======+=======+=======+=======+=======+
| **NaOH** (Mw 40) | 4 г   | 8 г   | 10 г  | 12 г  | 16    | 20 г  |
+------------------+-------+-------+-------+-------+-------+-------+

-   Довести mQ до нужного объема

-   Хранить при КТ

    [Инструкция от Sigma](https://www.sigmaaldrich.com/deepweb/assets/sigmaaldrich/product/documents/175/308/s0899pis.pdf)
