---
title: "Буфер E (EB)"
author: "Romanov Stanislav"
date: "21 10 2021"
tags: ["Буфер E","EB","Очистка ДНК на колонках"]
---

```{r echo=FALSE}

blogdown::shortcode("notice", "info",.content = "Буфер E применяется для элюции ДНК из колонок с силикой.  Слабощелочной pH и низкая ионная сила способствуют высвобождению ДНК с поверхности диоксида кремния. pH буфер препятствует  апуринизации и бета-элиминированию ДНК, что увеличивает срок хранения образцов. Буфер не содержит ЭДТА, поэтому не ингибирует ПЦР.")

```

### Необходимые компоненты

-   [1М TrisHCl](/labreagents/buffers/tris) (pH 8.5)
-   mQ

### Буфер E

-   Развести **1 M TrisHCl** (pH 8.5) до 10 мМ (в 100 раз) с помощью mQ 
-   Стерилизовать автоклавированием или фильтрацией, расфасовать
-   Хранить при комнатной температуре

```{r echo=FALSE}

blogdown::shortcode("notice", "tip",.content = "Буфер EB из набора Qiagen Mini/Midi/MaxiPrep имеет аналогичный состав.")

```

```{r echo=FALSE}

blogdown::shortcode("notice", "tip",.content = "Буфер E или EB можно использовать для разведения ДНК в тех случаях, когда присутствие ЭДТА нежелательно. Например, для разведения стандартов для количественной ПЦР.")

```
